# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quiero Mas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Google/SignIn'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'SWRevealViewController'
  pod 'SDWebImage'

  # Pods for Quiero Mas

end
